-- Generato da scripts/gen-seed.mjs: prezzi e voci del catalogo
insert into public.catalog_items (key, category, label, price, active, sort_order) values
  ('shape:rotonda', 'shape', 'Rotonda', 0.00, true, 0),
  ('shape:quadrata', 'shape', 'Quadrata', 0.00, true, 1),
  ('shape:rettangolare', 'shape', 'Rettangolare', 0.00, true, 2),
  ('shape:cuore', 'shape', 'Cuore', 0.00, true, 3),
  ('size:s', 'size', 'Piccola', 28.00, true, 4),
  ('size:m', 'size', 'Media', 40.00, true, 5),
  ('size:l', 'size', 'Grande', 58.00, true, 6),
  ('size:xl', 'size', 'Extra', 80.00, true, 7),
  ('tier:1', 'tier', '1 piano', 0.00, true, 8),
  ('tier:2', 'tier', '2 piani', 35.00, true, 9),
  ('tier:3', 'tier', '3 piani', 75.00, true, 10),
  ('sponge:classico', 'sponge', 'Pan di Spagna classico', 0.00, true, 11),
  ('sponge:cacao', 'sponge', 'Pan di Spagna al cacao', 2.00, true, 12),
  ('sponge:redvelvet', 'sponge', 'Red velvet', 4.00, true, 13),
  ('sponge:carota', 'sponge', 'Carota e mandorle', 3.00, true, 14),
  ('filling:pasticcera', 'filling', 'Crema pasticcera', 0.00, true, 15),
  ('filling:chantilly', 'filling', 'Chantilly', 0.00, true, 16),
  ('filling:cioccolato', 'filling', 'Crema al cioccolato', 2.00, true, 17),
  ('filling:nocciola', 'filling', 'Crema alla nocciola', 3.00, true, 18),
  ('filling:pistacchio', 'filling', 'Crema al pistacchio', 5.00, true, 19),
  ('filling:frutti', 'filling', 'Chantilly e frutti di bosco', 4.00, true, 20),
  ('covering:panna', 'covering', 'Panna montata', 0.00, true, 21),
  ('covering:buttercream', 'covering', 'Buttercream', 6.00, true, 22),
  ('covering:pdz', 'covering', 'Pasta di zucchero', 12.00, true, 23),
  ('covering:ganache', 'covering', 'Ganache al cioccolato', 8.00, true, 24),
  ('covering:naked', 'covering', 'Naked cake (senza copertura)', 0.00, true, 25),
  ('garnish:frutta', 'garnish', 'Frutta fresca', 6.00, true, 26),
  ('garnish:macarons', 'garnish', 'Macarons', 9.00, true, 27),
  ('garnish:fiori', 'garnish', 'Fiori eduli', 7.00, true, 28),
  ('garnish:rosette', 'garnish', 'Rosette di crema', 4.00, true, 29),
  ('garnish:meringhe', 'garnish', 'Meringhette', 4.00, true, 30),
  ('garnish:perle', 'garnish', 'Perline di zucchero', 3.00, true, 31),
  ('garnish:scaglie', 'garnish', 'Scaglie di cioccolato', 3.00, true, 32),
  ('garnish:drip', 'garnish', 'Colata di cioccolato (drip)', 5.00, true, 33),
  ('garnish:oro', 'garnish', 'Foglia oro alimentare', 8.00, true, 34),
  ('model:orsetto', 'model', 'Orsetto', 18.00, true, 35),
  ('model:unicorno', 'model', 'Unicorno', 22.00, true, 36),
  ('model:dinosauro', 'model', 'Dinosauro', 22.00, true, 37),
  ('model:pallone', 'model', 'Pallone da calcio', 15.00, true, 38),
  ('model:auto', 'model', 'Macchinina', 20.00, true, 39),
  ('model:corona', 'model', 'Corona', 16.00, true, 40),
  ('model:sposi', 'model', 'Sposi', 35.00, true, 41),
  ('model:cuore', 'model', 'Cuore', 12.00, true, 42),
  ('topper:cialda', 'topper', 'Immagine stampata (cialda)', 12.00, true, 43),
  ('topper:numero', 'topper', 'Numero 3D', 10.00, true, 44),
  ('lettering:scritta', 'lettering', 'Scritta', 3.00, true, 45)
on conflict (key) do update set
  category = excluded.category,
  label = excluded.label,
  price = excluded.price,
  sort_order = excluded.sort_order,
  updated_at = now();
